### ISSUE TITLE
Is there a way to prevent plot from displaying in jupyter?

### ISSUE THREAD

**Issue by JakubWabinski** [tomkwok/calplot#15]
Hello,

I was wondering if it is possible to prevent plots from displaying and simply saving to files. I have to loop over like 400 datasets and I don't want the code to display all the calendars. I thinki that matplotlib allows this but does calplot as well?

Thanks in advance!

Kuba

**Comment by tomkwok** [comment]
You can just do `plt.close()` after `fig.savefig(...)`

**Comment by JakubWabinski** [comment]
OMG... That really works - thanks  :) Must've missed something.
