### ISSUE TITLE
Unexpected timestamp key errors

### ISSUE THREAD

**Issue by JakubWabinski** [tomkwok/calplot#16]
Here I am again. My case is to loop over ~400 files (GNSS data - for a given date either True or False) and create calendars. For some strange reason around 20 of the files cause errors when using calplot (whereas others are generated without any issues). The problematic ones raise a series of keyerrors related with timestamps - 1st day of a year (in different formats: eg.: 154630080000000000, Timestamp('2019-01-01 00:00:00', 2019). Looks like the algorithm starts plotting with False values and draws the calendars correctly until the error occurs. Then the following years are not plotted.

I triple-checked the data. There are no issues (unexpected values, data holes, column formats). Also tried plotting simple time series using plt and it works fine. The scripts returns errors both when data are pulled from Postgres and local files.

Do you have any hints what may cause these errors? Have any of you encountered similar problems? Please find screenshots attached.

Thank you in advance

<b>The code used:</b>
<i>BLGR = df[df['nasza_nazwa'] == 'BLGR']
events = BLGR[ ['status', 'epoch'] ].set_index('epoch').squeeze()

calplot.calplot(events, 
                  cmap = 'RdYlGn', 
                  edgecolor = 'black',
                  colorbar = True,
                  daylabels= ['pon.','wt.','śr.','czw.','pt.','sob.','niedz.'],
                  monthlabels = ['STY', 'LUT', 'MAR', 'KWI', 'MAJ', 'CZE', 'LIP', 'SIE', 'WRZ', 'PAŹ', 'LIS', 'GRU'],
                  suptitle = 'BLGR'
                 );
plt.close()</i>

![image](https://user-images.githubusercontent.com/75029310/132351659-930268f9-8e8c-45d8-bded-b7c5ed8cf59d.png)
![image](https://user-images.githubusercontent.com/75029310/132351860-d8954f6f-e3b8-4a88-90ab-83240be1b5b1.png)
![image](https://user-images.githubusercontent.com/75029310/132351901-e480302d-ac38-4f03-97a9-48b381e7a279.png)
![image](https://user-images.githubusercontent.com/75029310/132351938-94ce7110-2dbb-423d-a332-ee19cb605964.png)

**Comment by matahi** [comment]
```
    # Default to dropping zero values for a series with over 50% of rows being zero.
    if by_day[by_day == 0].count() > 0.5 * by_day.count():
        dropzero = True

    if dropzero:
        by_day = by_day.replace({0: np.nan}).dropna()

```
Issue is coming from this. Basically the function is trying to plot every year but for some years where most of your data is zero you will try to plot an empty series so it returns an error.

**Comment by JakubWabinski** [comment]
Thanks matahi, that explains a lot. Is there a way to disable/ignore it?

I'm rather new to GitHub. How can I enter the source code?
