### ISSUE TITLE
Minimum example won't show anything

### ISSUE THREAD

**Issue by gary094** [tomkwok/calplot#3]
Hi,

I just tried your minimum example provided in the documentation like this:

```
import numpy as np; np.random.seed(sum(map(ord, 'calplot')))
import pandas as pd
import calplot

all_days = pd.date_range('1/1/2019', periods=730, freq='D')
days = np.random.choice(all_days, 500)
events = pd.Series(np.random.randn(len(days)), index=days)
calplot.calplot(events, cmap='YlGn')
```

however it does not show anything upon execution program just exits, exit code is 0 
python version: 3.6
pandas: 1.1.4
calplot: 0.1.4
numpy: 1.19.4

Could you help me please figuring out whats wrong?

**Comment by tomkwok** [comment]
Please execute the code in a Jupyter notebook
