### ISSUE TITLE
Colorbar disabled when input data has only 1 unique value

### ISSUE THREAD

**Issue by carsonyl** [tomkwok/calplot#5]
I'm working with input data that's all ones, and relying on `how="sum"` . But this means I only have 1 unique value, which triggers code that blocks the colorbar from being drawn:

https://github.com/tomkwok/calplot/blob/87816ba9dc9b9df9304b700162aa462d56a14f24/calplot/calplot.py#L288-L289

Removing those lines fixes the problem and shows a colorbar with the expected min/max.

**Comment by tomkwok** [comment]
Changed behavior w.r.t. different values for `colorbar` attribute as follows. This should fix your problem.

- `colorbar=None` (default): if there is more than one unique value, show colorbar
- `colorbar=True`: always show colorbar
- `colorbar=False`: never show colorbar

See calplot release 0.1.7.1
